services:
  - type: web
    name: mail
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn mail.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project3.settings
      - key: SECRET_KEY
        generateValue: true
